name: myfluttercrypto
description: Cross-platform application developed with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.20211004+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  encrypt: ^5.0.1
  url_launcher: ^6.0.11
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  desktop_window: ^0.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"

flutter:

  uses-material-design: true
  generate: true